[workspace]
authors = ["Willi Rath <wrath@geomar.de>"]
channels = ["conda-forge"]
name = "2025-11-09_oldparcels"
platforms = ["osx-64"]
version = "0.1.0"

[environments]
parcels-v09 = { features = ["parcels-v09"] }

[feature.parcels-v09.tasks.bootstrap-v09]
cmd = "pip install 'cgen<2020' 'progressbar<3' 'pymbolic<2020'"

[feature.parcels-v09.tasks.parcels-v09-python]
cmd = "python"
env = { PYTHONPATH = "./parcels-v09" }

[feature.parcels-v09.dependencies]
python = "2.7.*"
pip = ">=20.1.1,<21"
setuptools = "<45"
wheel = "<0.35"
cython = "<0.29"
numpy = "1.16.*"
scipy = "1.2.*"
netcdf4 = "1.5.*"
libnetcdf = ">=4.7.3,<5"
xarray = "0.11.*"
dask = "1.2.*"
pytest = "<5"
click = "7.*"
future = ">=0.18.2,<0.19"
enum34 = ">=1.1.10,<2"
