[workspace]
authors = ["Willi Rath <wrath@geomar.de>"]
channels = ["conda-forge"]
name = "2025-11-09_oldparcels"
platforms = ["osx-64"]
version = "0.1.0"

[environments]
parcels-v09 = { features = ["parcels-v09"] }
parcels-v105 = { features = ["parcels-v105"] }
parcels-v111 = { features = ["parcels-v111"] }
parcels-v242 = { features = ["parcels-v242"] }
parcels-v314 = { features = ["parcels-v314"] }

[feature.parcels-v09.tasks.bootstrap-v09]
cmd = "bash scripts/bootstrap-parcels-v09.sh"

[feature.parcels-v09.tasks.parcels-v09-python]
cmd = 'env PYTHONPATH="$PWD/parcels-v09" python'

[feature.parcels-v09.tasks.parcels-v09-notebook]
cmd = 'env PYTHONPATH="$PWD/parcels-v09" jupyter notebook --notebook-dir=parcels-v09/examples --NotebookApp.open_browser=False'

[feature.parcels-v09.dependencies]
python = "2.7.*"
pip = ">=20.1.1,<21"
setuptools = "<45"
wheel = "<0.35"
cython = "<0.29"
numpy = "1.16.*"
scipy = "1.2.*"
netcdf4 = "1.5.*"
libnetcdf = ">=4.7.3,<5"
xarray = "0.11.*"
dask = "1.2.*"
pytest = "<5"
click = "7.*"
future = ">=0.18.2,<0.19"
enum34 = ">=1.1.10,<2"
notebook = "<6"
netcdftime = ">=1.0.0a2,<2"

[feature.parcels-v105.tasks.bootstrap-v105]
cmd = "bash scripts/bootstrap-parcels-v105.sh"

[feature.parcels-v105.tasks.parcels-v105-python]
cmd = 'env PYTHONPATH="$PWD/parcels-v105" MPLCONFIGDIR="$PWD/.cache/matplotlib" python'

[feature.parcels-v105.tasks.parcels-v105-notebook]
cmd = 'env PYTHONPATH="$PWD/parcels-v105" MPLCONFIGDIR="$PWD/.cache/matplotlib" jupyter notebook --notebook-dir="$PWD/parcels-v105/parcels/examples" --NotebookApp.open_browser=False'

[feature.parcels-v105.dependencies]
python = "2.7.*"
pip = ">=20.1.1,<21"
setuptools = "<45"
wheel = "<0.35"
cython = "<0.29"
numpy = "1.16.*"
scipy = "1.2.*"
netcdf4 = "1.5.*"
libnetcdf = ">=4.7.3,<5"
xarray = "0.11.*"
dask = "1.2.*"
pytest = "<5"
click = "7.*"
future = ">=0.18.2,<0.19"
enum34 = ">=1.1.10,<2"
notebook = "<6"
netcdftime = ">=1.0.0a2,<2"
cachetools = ">=1,<6"
matplotlib = "2.2.*"
python-dateutil = "2.8.*"
six = ">=1.10.0,<2"
progressbar2 = "<4"

[feature.parcels-v111.tasks.bootstrap-v111]
cmd = "bash scripts/bootstrap-parcels-v111.sh"

[feature.parcels-v111.tasks.parcels-v111-python]
cmd = 'env PYTHONPATH="$PWD/parcels-v111" python'

[feature.parcels-v111.tasks.parcels-v111-notebook]
cmd = 'env PYTHONPATH="$PWD/parcels-v111" jupyter notebook --notebook-dir="$PWD/parcels-v111/parcels/examples" --NotebookApp.open_browser=False'

[feature.parcels-v111.dependencies]
python = "2.7.*"
pip = ">=20.1.1,<21"
setuptools = "<45"
wheel = "<0.35"
cython = "<0.29"
numpy = "1.16.*"
scipy = "1.2.*"
netcdf4 = "1.5.*"
libnetcdf = ">=4.7.3,<5"
xarray = "0.11.*"
dask = "1.2.*"
pytest = "<5"
click = "7.*"
future = ">=0.18.2,<0.19"
enum34 = ">=1.1.10,<2"
notebook = "<6"
netcdftime = ">=1.0.0a2,<2"
cachetools = ">=1,<6"
matplotlib = "2.2.*"
cftime = ">=1.0,<2"
python-dateutil = "2.8.*"
six = "1.16.*"
progressbar2 = "<4"

[feature.parcels-v242.tasks.bootstrap-v242]
cmd = "bash scripts/bootstrap-parcels-v242.sh"

[feature.parcels-v242.tasks.parcels-v242-python]
cmd = 'env PYTHONPATH="$PWD/parcels-v242" MPLCONFIGDIR="$PWD/.cache/matplotlib" python'

[feature.parcels-v242.tasks.parcels-v242-notebook]
cmd = 'env PYTHONPATH="$PWD/parcels-v242" MPLCONFIGDIR="$PWD/.cache/matplotlib" jupyter notebook --notebook-dir="$PWD/parcels-v242/docs/examples" --NotebookApp.open_browser=False'

[feature.parcels-v242.dependencies]
python = "3.10.*"
pip = ">=23,<24"
setuptools = ">=68,<71"
wheel = ">=0.41,<0.44"
setuptools-scm = ">=7,<9"
cgen = ">=2020.1"
ffmpeg = ">=4,<6"
git = ">=2.40,<3"
notebook = ">=6.5,<7"
matplotlib = ">=3.7,<3.8"
netcdf4 = ">=1.6,<1.7"
libnetcdf = ">=4.9,<4.10"
numpy = ">=1.23,<1.24"
platformdirs = ">=3,<5"
psutil = ">=5.9,<6"
py = ">=1.11,<2"
pymbolic = ">=2022,<2024"
scipy = ">=1.9,<1.11"
tqdm = ">=4.65,<5"
xarray = ">=2023.5.0,<2024"
dask = ">=2023.5.1,<2024"
cftime = ">=1.6,<1.7"
nbval = ">=0.11,<0.12"
scikit-learn = ">=1.2,<1.4"
pykdtree = ">=1.3,<1.4"
zarr = ">=2.14,<2.16"
black = ">=23,<24"
isort = ">=5.12,<5.13"
pytest = ">=7.4,<8"
pytest-html = ">=3.2,<4"
coverage = ">=7,<8"
flake8 = ">=6,<7"
pre-commit = ">=3,<4"
pydocstyle = ">=6,<7"
ipython = ">=8.12,<8.13"
numpydoc = ">=1.5,<1.6"
nbsphinx = ">=0.9,<0.10"
sphinx = ">=5,<6"
pandoc = ">=2,<3"
pydata-sphinx-theme = ">=0.13,<0.14"
sphinx-autobuild = ">=2021.3,<2022"
myst-parser = ">=1,<2"

[feature.parcels-v314.tasks.bootstrap-v314]
cmd = "bash scripts/bootstrap-parcels-v314.sh"

[feature.parcels-v314.tasks.parcels-v314-python]
cmd = 'env PYTHONPATH="$PWD/parcels-v314" MPLCONFIGDIR="$PWD/.cache/matplotlib" python'

[feature.parcels-v314.tasks.parcels-v314-notebook]
cmd = 'env PYTHONPATH="$PWD/parcels-v314" MPLCONFIGDIR="$PWD/.cache/matplotlib" jupyter notebook --notebook-dir="$PWD/parcels-v314/docs/examples" --NotebookApp.open_browser=False'

[feature.parcels-v314.dependencies]
python = "3.11.*"
pip = ">=23.2,<24"
setuptools = ">=70,<71"
wheel = ">=0.42,<0.45"
setuptools-scm = ">=7,<9"
cgen = ">=2020.1"
ffmpeg = ">=4,<6"
jupyter = ">=1,<2"
notebook = ">=7,<8"
matplotlib = ">=3.8,<3.9"
netcdf4 = ">=1.6,<1.7"
libnetcdf = ">=4.9,<4.10"
numpy = ">=1.26,<1.27"
platformdirs = ">=3,<5"
psutil = ">=5.9,<6"
pymbolic = ">=2022,<2024"
scipy = ">=1.11,<1.13"
tqdm = ">=4.66,<5"
xarray = ">=2023.9.0,<2024.5"
dask = ">=2023.9.0,<2024.5"
cftime = ">=1.6,<1.7"
scikit-learn = ">=1.3,<1.4"
zarr = ">=2.14,<3"
trajan = ">=0.1,<0.2"
nbval = ">=0.11,<0.12"
pytest = ">=7.4,<8"
pytest-html = ">=3.2,<4"
coverage = ">=7,<8"
mypy = ">=1.4,<1.8"
types-tqdm = ">=4.66.0.4,<4.67"
types-psutil = ">=5.9.5,<5.10"
pre-commit = ">=3,<4"
ipython = ">=8.18,<8.19"
numpydoc = ">=1.6,<1.7"
nbsphinx = ">=0.9,<0.10"
sphinx = ">=7,<8"
pandoc = ">=2,<3"
pydata-sphinx-theme = ">=0.14,<0.15"
sphinx-autobuild = ">=2021.3,<2022"
myst-parser = ">=2,<3"
